name: Multiplatform Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: true

      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
        build_type: [Release]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: arm64-osx
          - os: macos-13
            triplet: x64-osx

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: lukka/get-cmake@latest

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: '**/vcpkg.json'
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'

    - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
      uses: lukka/run-cmake@v10
      with:
        # This is the default path to the CMakeLists.txt along side the
        # CMakePresets.json. Change if you need have CMakeLists.txt and CMakePresets.json
        # located elsewhere.
        # cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'

        # You could use CMake workflow presets defined in the CMakePresets.json
        # with just this line below. Note this one cannot be used with any other
        # preset input, it is mutually exclusive.
        # workflowPreset: 'workflow-name'

        # This is the name of the CMakePresets.json's configuration to use to generate
        # the project files. This configuration leverages the vcpkg.cmake toolchain file to
        # run vcpkg and install all dependencies specified in vcpkg.json.
        # configurePreset: 'ninja-multi-vcpkg'

        # Additional arguments can be appended to the cmake command.
        # This is useful to reduce the number of CMake's Presets since you can reuse
        # an existing preset with different variables.
        # configurePresetAdditionalArgs: "['-DENABLE_YOUR_FEATURE=1']"

        # This is the name of the CMakePresets.json's configuration to build the project.
        # buildPreset: 'ninja-multi-vcpkg'
        # Additional arguments can be appended when building, for example to specify the
        # configuration to build.
        # This is useful to reduce the number of CMake's Presets you need in CMakePresets.json.
        buildPresetAdditionalArgs: "['--config Release']"
          
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os == 'macos-13' && 'macos-intel' || matrix.os == 'macos-latest' && 'macos-arm64' || matrix.os }}
        path: ${{ steps.strings.outputs.build-output-dir }}/dist/
